"""add languages

Revision ID: 5fffea5a766d
Revises: ea2604b68efe
Create Date: 2023-12-09 12:57:52.585224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5fffea5a766d'
down_revision: Union[str, None] = 'ea2604b68efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

languages_table = sa.table(
        "languages",
        sa.column('language_code', sa.String),
        sa.column('local_name', sa.String),
        sa.column('language_name', sa.String),
    )

languages = [
    dict(
        language_code='en',
        local_name='English',
        language_name='English',
    ),
    dict(
        language_code='es',
        local_name='Español',
        language_name='Spanish',
    ),
    dict(
        language_code='fr',
        local_name='Français',
        language_name='French',
    ),
    dict(
        language_code='de',
        local_name='Deutsch',
        language_name='German',
    ),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    conn.execute(
        languages_table.insert().values(languages)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    conn.execute(
        languages_table.delete()
    )
    # ### end Alembic commands ###
