"""set a server_default value false

Revision ID: 6ff320a631e9
Revises: 67a7fb50cb20
Create Date: 2023-12-10 14:41:55.717797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6ff320a631e9'
down_revision: Union[str, None] = '67a7fb50cb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'single_message',
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.false(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'single_message',
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    nullable=True)
    # ### end Alembic commands ###
