"""init db

Revision ID: dfa4aa4f8db5
Revises: 
Create Date: 2023-12-06 06:40:09.550145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfa4aa4f8db5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpt_models',
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.Column('model_name', sa.VARCHAR(length=32), nullable=False),
                    sa.Column('verbose_name', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('max_context_limit', sa.INTEGER(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('model_id'),
                    sa.UniqueConstraint('model_name')
                    )
    op.create_table('languages',
                    sa.Column('language_id', sa.Integer(), nullable=False),
                    sa.Column('language_code', sa.VARCHAR(length=7), nullable=False),
                    sa.Column('local_name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('language_name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('language_id'),
                    sa.UniqueConstraint('language_code')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('full_name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('language_id', sa.Integer(), nullable=False),
                    sa.Column('model_id', sa.Integer(), nullable=False),
                    sa.Column('auto_transcription', sa.BOOLEAN(), nullable=False),
                    sa.Column('auto_speech', sa.BOOLEAN(), nullable=False),
                    sa.Column('single_message', sa.BOOLEAN(), nullable=False),
                    sa.Column('user_profile', sa.VARCHAR(length=1500), nullable=True),
                    sa.Column('response_profile', sa.VARCHAR(length=1500), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
                    sa.ForeignKeyConstraint(['model_id'], ['gpt_models.model_id'], ),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('languages')
    op.drop_table('gpt_models')
    # ### end Alembic commands ###
