"""add server_default

Revision ID: ea2604b68efe
Revises: 2de217473580
Create Date: 2023-12-09 12:43:18.076951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ea2604b68efe'
down_revision: Union[str, None] = '2de217473580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "auto_transcription",
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.false(),
                    nullable=False
                    )
    op.alter_column("users", "auto_speech",
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.false(),
                    nullable=False
                    )
    op.alter_column("users", "single_message",
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.false(),
                    nullable=False
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "auto_transcription",
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    nullable=True
                    )
    op.alter_column("users", "auto_speech",
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    nullable=True
                    )
    op.alter_column("users", "single_message",
                    existing_type=sa.BOOLEAN(),
                    server_default=None,
                    nullable=True
                    )

    # ### end Alembic commands ###
